
# GHA on publish
name: module deployment
on:
  push:
    branches: 
      - dev
    paths:
      - 'infrastructure/modules/**'

jobs:
  zip-tf-modules-and-send-to-s3:
    runs-on: ubuntu-latest
    container: python:3.10.1-slim-buster
    timeout-minutes: 3

    permissions:
      contents: 'read'
      id-token: 'write'

    steps:
      - name: Checkout branch
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          pip3 install -r infrastructure/module_deployment/requirements.txt

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          role-to-assume: ${{ secrets.AWS_ROLE }}
          aws-region: "us-east-1"
          role-duration-seconds: 1200

      - name: ZIP Modules and ship to S3
        env:
          BUCKET_NAME: ${{ secrets.AWS_BUCKET }}
        run: |
          python3 infrastructure/module_deployment/main.py
